// A to Zero — built-in fallback catalog.
// Used only when the live product API is unreachable (fully offline use).
// All products here are fictional. Prices are for entertainment only.

const BUILTIN_CATEGORIES = [
  { id: "electronics", name: "Electronics", emoji: "🎧" },
  { id: "home",        name: "Home & Kitchen", emoji: "🏠" },
  { id: "books",       name: "Books", emoji: "📚" },
  { id: "toys",        name: "Toys & Games", emoji: "🧸" },
  { id: "fashion",     name: "Fashion", emoji: "👟" },
  { id: "sports",      name: "Sports & Outdoors", emoji: "🏕️" },
  { id: "beauty",      name: "Beauty & Care", emoji: "🧴" },
  { id: "pets",        name: "Pet Supplies", emoji: "🐾" },
];

const BUILTIN_PRODUCTS = [
  // Electronics
  { id: "p001", cat: "electronics", emoji: "🎧", name: "SoundNimbus Pro Wireless Noise-Cancelling Headphones — Over-Ear, 40h Battery, Midnight Black",
    price: 279.99, was: 349.99, rating: 4.7, reviews: 48213, prime: true,
    blurb: "Silence the world, keep the music. Adaptive ANC, plush memory-foam cups, and a battery that outlasts your longest day.",
    bullets: ["Adaptive noise cancellation with transparency mode", "40-hour battery, 5-min charge = 4 hours playback", "Multipoint Bluetooth 5.3 — two devices at once", "Foldable design with premium travel case"] },
  { id: "p002", cat: "electronics", emoji: "⌚", name: "PulseTrack 7 Smart Watch — Fitness, Sleep & Heart Tracking, 10-Day Battery, AMOLED",
    price: 149.00, was: 199.00, rating: 4.5, reviews: 31877, prime: true,
    blurb: "Your wrist just got smarter. Tracks everything from steps to sleep stages, and still looks great at dinner.",
    bullets: ["1.4\" always-on AMOLED display", "120+ workout modes with auto-detect", "10-day typical battery life", "5 ATM water resistance"] },
  { id: "p003", cat: "electronics", emoji: "🔊", name: "BoomPebble Mini Bluetooth Speaker — Waterproof, 24h Playtime, Ocean Blue",
    price: 39.99, was: 59.99, rating: 4.6, reviews: 92455, prime: true,
    blurb: "Pocket-sized thunder. Surprisingly big sound from a speaker that fits in your palm and survives the pool.",
    bullets: ["IPX7 fully waterproof — it floats!", "24 hours of playtime per charge", "Pair two for true stereo", "Built-in mic for calls"] },
  { id: "p004", cat: "electronics", emoji: "⌨️", name: "ClackForge 75 Mechanical Keyboard — Hot-Swap, RGB, Gasket Mount, Cream Switches",
    price: 89.99, was: 119.99, rating: 4.8, reviews: 12034, prime: true,
    blurb: "Thock heaven. A gasket-mounted 75% board that sounds like rain on a tin roof and types like a dream.",
    bullets: ["Hot-swappable switches, no soldering", "Pre-lubed cream linear switches", "South-facing RGB with 19 effects", "Tri-mode: USB-C, 2.4G, Bluetooth"] },
  { id: "p005", cat: "electronics", emoji: "📷", name: "SnapWren Instant Camera — Retro Design, Auto-Flash, Includes 20 Sheets of Film",
    price: 74.50, was: 89.99, rating: 4.4, reviews: 8765, prime: false,
    blurb: "Memories you can hold. Point, shoot, shake (you don't need to, but you will), and watch the moment appear.",
    bullets: ["Credit-card-size instant prints", "Auto exposure & flash", "Selfie mirror on the front", "Retro two-tone design"] },

  // Home & Kitchen
  { id: "p101", cat: "home", emoji: "☕", name: "MorningRitual 12-Cup Programmable Coffee Maker — Thermal Carafe, Bold Brew Mode",
    price: 64.99, was: 84.99, rating: 4.5, reviews: 27891, prime: true,
    blurb: "Wake up to victory. Programs tonight, brews at dawn, keeps it hot for hours without cooking the flavor.",
    bullets: ["24-hour programmable timer", "Double-wall thermal carafe", "Bold & 1-4 cup small-batch modes", "Self-clean cycle with reminder"] },
  { id: "p102", cat: "home", emoji: "🍳", name: "HearthStone 10-Piece Ceramic Non-Stick Cookware Set — Sage Green, Oven Safe",
    price: 129.00, was: 179.00, rating: 4.6, reviews: 15320, prime: true,
    blurb: "Cook like you mean it. Slick ceramic coating, stay-cool handles, and a color that makes the kitchen happier.",
    bullets: ["Toxin-free ceramic non-stick", "Oven safe to 450°F", "Works on all cooktops incl. induction", "Dishwasher safe (but hand-wash lasts longer)"] },
  { id: "p103", cat: "home", emoji: "🛋️", name: "CloudNest Weighted Blanket 15 lb — Cooling Bamboo Cover, Queen, Dusk Grey",
    price: 59.99, was: 79.99, rating: 4.7, reviews: 44102, prime: true,
    blurb: "A hug in blanket form. Evenly-distributed glass beads and a cooling cover for the deepest sleep of your week.",
    bullets: ["Premium glass-bead fill, zero rustle", "Removable, washable bamboo cover", "Sleeps cool — no overheating", "Even weight distribution stitching"] },
  { id: "p104", cat: "home", emoji: "🪴", name: "TerraTrio Self-Watering Planter Set (3-Pack) — Matte White, Indoor Herb Garden",
    price: 32.99, was: null, rating: 4.3, reviews: 6540, prime: true,
    blurb: "Plants that forgive you. A water reservoir and wick system keep your herbs alive through your busiest weeks.",
    bullets: ["2-week water reservoir", "Water-level window", "Drainage-safe for indoor shelves", "Fits standard windowsills"] },
  { id: "p105", cat: "home", emoji: "💡", name: "GlowSphere Smart Lamp — 16M Colors, Sunrise Alarm, App & Voice Control",
    price: 45.99, was: 55.99, rating: 4.4, reviews: 19233, prime: true,
    blurb: "Set the mood, any mood. From focus-white to sunset-amber, plus a sunrise alarm that beats any buzzer.",
    bullets: ["16 million colors + warm-to-cool whites", "Sunrise/sunset simulation alarm", "Music sync mode", "Works with voice assistants"] },

  // Books
  { id: "p201", cat: "books", emoji: "📘", name: "The Cartographer of Lost Hours — A Novel (Hardcover)",
    price: 24.49, was: 28.99, rating: 4.8, reviews: 21456, prime: true,
    blurb: "The year's most talked-about debut. A mapmaker discovers the blank spaces on his maps are places time forgot.",
    bullets: ["Winner — Fictional Book Prize 2025", "416 pages of gorgeous prose", "Deckled edges, ribbon bookmark", "\"Impossible to put down\" — everyone"] },
  { id: "p202", cat: "books", emoji: "📗", name: "Enough: The Gentle Art of Wanting What You Have (Paperback)",
    price: 16.99, was: 18.99, rating: 4.9, reviews: 38771, prime: true,
    blurb: "The anti-shopping book, sold here without irony. Practical, kind, and quietly life-changing.",
    bullets: ["12 practices for contentment", "Includes the famous '72-hour want list'", "288 pages", "Book-club discussion guide included"] },
  { id: "p203", cat: "books", emoji: "📙", name: "Midnight at the Noodle Museum — Cozy Mystery #1 (Paperback)",
    price: 13.59, was: 15.99, rating: 4.6, reviews: 9812, prime: true,
    blurb: "A retired chef, a stolen recipe, and a museum where nothing is quite al dente. First in the beloved series.",
    bullets: ["Book 1 of 7 in the series", "Includes 5 real noodle recipes", "352 pages", "No gore, all charm"] },
  { id: "p204", cat: "books", emoji: "📕", name: "The Big Book of Useless Machines — 50 Absurd Engineering Projects (Hardcover)",
    price: 21.99, was: 26.99, rating: 4.7, reviews: 5233, prime: false,
    blurb: "Build a box whose only function is to turn itself off. Delightfully pointless weekend engineering.",
    bullets: ["50 fully-illustrated projects", "Beginner to 'why would you' difficulty", "Full parts lists included", "The perfect gift for tinkerers"] },

  // Toys & Games
  { id: "p301", cat: "toys", emoji: "🧩", name: "MegaMosaic 2000-Piece Gradient Puzzle — 'Dawn Over the Pacific'",
    price: 27.99, was: 34.99, rating: 4.7, reviews: 11240, prime: true,
    blurb: "2000 pieces of pure gradient chaos. Somewhere between meditation and madness. Frame-worthy when done.",
    bullets: ["Premium matte anti-glare finish", "Precision-cut, satisfying snap", "Poster reference included", "27\" × 38\" finished size"] },
  { id: "p302", cat: "toys", emoji: "🦖", name: "RoarBot Interactive Robot Dinosaur — Voice Commands, App Programmable, Ages 6+",
    price: 79.99, was: 99.99, rating: 4.5, reviews: 8433, prime: true,
    blurb: "Half pet, half robot, all Cretaceous. Responds to 40 voice commands and learns tricks. Does not eat homework (usually).",
    bullets: ["40+ voice commands", "Drag-and-drop coding app for kids", "Touch sensors on head and back", "2-hour play per charge"] },
  { id: "p303", cat: "toys", emoji: "🎲", name: "Tavern of Wonders — The Fantasy Strategy Board Game (2-6 Players)",
    price: 44.99, was: 54.99, rating: 4.8, reviews: 15877, prime: true,
    blurb: "Run a magical tavern, hire questionable heroes, sabotage your friends. 60-90 minutes of glorious betrayal.",
    bullets: ["2-6 players, ages 10+", "150+ illustrated cards", "45 custom wooden meeples", "Solo mode included"] },
  { id: "p304", cat: "toys", emoji: "🪁", name: "SkyDancer Pro Stunt Kite — Dual Line, 48\" Wingspan, Rainbow Ripstop",
    price: 34.50, was: null, rating: 4.4, reviews: 3201, prime: true,
    blurb: "The sky is your canvas. Loops, dives, and figure-eights with a kite that practically flies itself.",
    bullets: ["Dual-line precision control", "Rip-stop nylon + fiberglass frame", "Flies in 5-25 mph winds", "Includes winder, lines & bag"] },

  // Fashion
  { id: "p401", cat: "fashion", emoji: "👟", name: "StrideCloud Everyday Sneakers — Knit Upper, Cloud Foam, Unisex, Storm Grey",
    price: 68.00, was: 85.00, rating: 4.5, reviews: 22156, prime: true,
    blurb: "Walking on clouds is no longer a metaphor. Featherlight knit with foam that gives back every step.",
    bullets: ["Breathable one-piece knit upper", "Energy-return cloud foam midsole", "Machine washable", "Vegan materials throughout"] },
  { id: "p402", cat: "fashion", emoji: "🧣", name: "NordicMist Oversized Wool-Blend Scarf — Herringbone, Camel & Cream",
    price: 29.99, was: 39.99, rating: 4.6, reviews: 7654, prime: true,
    blurb: "The scarf that makes every coat look expensive. Big enough to be a blanket in emergencies (movie theaters).",
    bullets: ["70\" × 26\" — properly oversized", "Soft wool blend, zero itch", "Classic herringbone weave", "Fringed ends"] },
  { id: "p403", cat: "fashion", emoji: "🕶️", name: "HorizonLine Polarized Sunglasses — Classic Round, Tortoise Shell, UV400",
    price: 24.99, was: 34.99, rating: 4.3, reviews: 13890, prime: true,
    blurb: "Instant cool, zero glare. Polarized lenses in a frame that has never once gone out of style.",
    bullets: ["Polarized UV400 lenses", "Featherweight acetate frame", "Spring hinges for comfy fit", "Case + cleaning cloth included"] },
  { id: "p404", cat: "fashion", emoji: "🎒", name: "CityTrek 25L Commuter Backpack — Water-Resistant, Laptop Sleeve, Midnight Navy",
    price: 54.99, was: 69.99, rating: 4.7, reviews: 18432, prime: true,
    blurb: "Organized chaos, solved. A pocket for everything, a sleeve for the laptop, and a secret one for snacks.",
    bullets: ["Padded 16\" laptop compartment", "Water-resistant recycled fabric", "Luggage pass-through strap", "Hidden anti-theft pocket"] },

  // Sports & Outdoors
  { id: "p501", cat: "sports", emoji: "🧘", name: "ZenGround Extra-Thick Yoga Mat — 8mm, Non-Slip, Eucalyptus Green, Strap Included",
    price: 36.99, was: 46.99, rating: 4.6, reviews: 25671, prime: true,
    blurb: "Your knees called — they're thrilled. Extra cushion, serious grip, and a strap so it actually leaves the house.",
    bullets: ["8mm cushion, joint-friendly", "Wet & dry non-slip texture", "72\" × 26\" — room to flow", "Carrying strap included"] },
  { id: "p502", cat: "sports", emoji: "⛺", name: "StarPort 4-Person Camping Tent — 60-Second Setup, Skylight Mesh Roof",
    price: 119.00, was: 149.00, rating: 4.5, reviews: 9340, prime: true,
    blurb: "Sixty seconds from car to camp. Pop the hub, stake the corners, and fall asleep under the mesh skylight.",
    bullets: ["Instant hub design — 60s setup", "Full mesh roof for stargazing", "Rainfly + 3000mm waterproof floor", "Fits two queen air mattresses"] },
  { id: "p503", cat: "sports", emoji: "🚴", name: "VeloBeam USB-C Bike Light Set — 800 Lumens Front + Smart Brake Tail Light",
    price: 42.99, was: 52.99, rating: 4.7, reviews: 6785, prime: true,
    blurb: "Be seen, be safe, be bright. The tail light senses braking and flares up like a car's — drivers notice.",
    bullets: ["800-lumen front, 5 modes", "Accelerometer brake-flash tail light", "USB-C fast charging", "IPX6 stormproof"] },
  { id: "p504", cat: "sports", emoji: "🏸", name: "FeatherStorm Badminton Set for 4 — Net, Rackets, Shuttles & Carry Bag",
    price: 49.99, was: null, rating: 4.2, reviews: 4102, prime: true,
    blurb: "Backyard tournaments start here. Everything four players need, in one bag, up in five minutes.",
    bullets: ["4 lightweight steel rackets", "Adjustable-height net (badminton to volleyball... okay, badminton)", "6 nylon shuttlecocks", "All-in-one shoulder bag"] },

  // Beauty & Care
  { id: "p601", cat: "beauty", emoji: "🧴", name: "DewDrop 5-Step Skincare Ritual Set — Cleanser to Moisturizer, All Skin Types",
    price: 48.99, was: 64.99, rating: 4.5, reviews: 16754, prime: true,
    blurb: "Your skin's new favorite routine. Five gentle steps, zero guesswork, one very smug glow.",
    bullets: ["Cleanser, toner, serum, eye cream, moisturizer", "Fragrance-free & dermatologist tested", "Cruelty-free & vegan", "Recyclable packaging"] },
  { id: "p602", cat: "beauty", emoji: "💆", name: "TheraKnead Shiatsu Neck & Shoulder Massager — Heat, 8 Nodes, Overheat Protection",
    price: 54.99, was: 69.99, rating: 4.6, reviews: 29811, prime: true,
    blurb: "Fire your knots. Eight deep-kneading nodes and gentle heat turn desk-shoulders back into human shoulders.",
    bullets: ["8 deep-tissue shiatsu nodes", "Soothing heat function", "3 speeds, auto-reverse", "15-min auto shutoff"] },
  { id: "p603", cat: "beauty", emoji: "🪥", name: "BrightOrbit Sonic Toothbrush — 5 Modes, 30-Day Battery, 4 Heads Included",
    price: 39.99, was: 59.99, rating: 4.4, reviews: 21309, prime: true,
    blurb: "40,000 gentle strokes a minute. Your dentist will ask what changed. Be mysterious.",
    bullets: ["40,000 VPM sonic cleaning", "5 modes incl. sensitive & whitening", "30-day battery per charge", "2-min timer with quad pacing"] },

  // Pets
  { id: "p701", cat: "pets", emoji: "🐱", name: "WhiskerFort Deluxe Cat Tree — 5 Levels, 2 Condos, Sisal Posts, 58\" Tall",
    price: 89.99, was: 119.99, rating: 4.6, reviews: 13455, prime: true,
    blurb: "A skyscraper for your supervisor. Five levels of napping, scratching, and judging you from above.",
    bullets: ["58\" tall, 5 platforms", "2 cozy condos + hammock", "Full sisal scratching posts", "Anti-tip wall strap included"] },
  { id: "p702", cat: "pets", emoji: "🐕", name: "FetchForever Automatic Ball Launcher — 3 Distance Settings, 6 Mini Balls",
    price: 64.99, was: 79.99, rating: 4.3, reviews: 7621, prime: true,
    blurb: "Infinite fetch, zero shoulder strain. Some dogs learn to reload it themselves. Prepare for that day.",
    bullets: ["10/20/30 ft launch settings", "6 dog-safe mini tennis balls", "AC or battery powered", "Safety sensor pauses near faces"] },
  { id: "p703", cat: "pets", emoji: "🐠", name: "AquaVista 5-Gallon Glass Aquarium Kit — LED Lid, Quiet Filter, Starter Guide",
    price: 74.99, was: 89.99, rating: 4.4, reviews: 5908, prime: false,
    blurb: "A tiny world on your desk. Everything included except the fish and the existential calm they provide.",
    bullets: ["Crystal glass, rounded corners", "7-color LED lighting lid", "Whisper-quiet 3-stage filter", "Beginner setup guide included"] },
];
